[package]
name = "fake-kasa"
version = "0.1.0"
authors = ["Ash Wolf <ninji@wuffs.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
